version: '3.8'

services:
  telegram_bot:
    container_name: buddymap
    build:
      context: .  # Указываем текущую директорию как контекст сборки
      dockerfile: Dockerfile  # Указываем имя Dockerfile
    image: telegram_bot_image  # Указываем имя для образа
    restart: always
    environment:
      - DATABASE_URL=postgres://user:beslan@postgres_db:5432/buddymap  # Укажите свои данные для подключения
    depends_on:
      - postgres_db  # Указываем зависимость от сервиса PostgreSQL
      - redis

  postgres_db:
    container_name: buddymap_db
    image: postgres:15   # Используем образ PostgreSQL
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: beslan  # Укажите имя пользователя
      POSTGRES_PASSWORD: beslan  # Укажите пароль
      POSTGRES_DB: buddymap  # Укажите имя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
  
  redis:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:  # Объявляем том для хранения данных PostgreSQL
